#!/usr/bin/env bash
# check if all parameters are provided
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
# assign parameters to variables

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

# check the exit status of scp
if [ $? -eq 0 ]
then
	echo "Transfer Scuccesfull"
else
	echo "Transfee error, Try again"
fi
