#!/usr/bin/env bash
# Installs, configures, and starts the server

# Update the list of available software packages
apt-get update

# Install Nginx web server with automatic "yes" responses to prompts
apt-get -y install nginx

# Allow incoming HTTP traffic through the firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create the web directory if it doesn't exist
mkdir -p /var/www/html/

# Set appropriate permissions for the web directory and its contents
sudo chmod -R 755 /var/www

# Create  "Hello World!" index page
echo 'Hello World!' > /var/www/html/index.html

# Define the Nginx server config
SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Redirect requests containing 'redirect_me' to a specific URL
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
    }
}"

# Apply the server config by writing it to the Nginx default site
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

# Check if Nginx is already running; start or restart
if [ "$(pgrep -c nginx)" -le 0 ]; then
    service nginx start
else
    service nginx restart
fi

